### PR TITLE
added ManagerProvider and AuctionProvider

### PR DESCRIPTION
**Pull request by salieflewis**

### CODE REVIEW

**Comment by salieflewis** [comment]
A few things here.

1. Hoping for some feedback on the approach to `AuctionProvider.tsx` 
2. How do I get [this site](https://dao-utils.public---assembly.com/examples) to build locally? Running `pnpm run dev` from the root of the repo takes you to the docs sites for dao-utils. I tried navigating into the sample app folder `cd/apps/next` and then running `pnpm run dev` from there but that is also not the answer. What am I missing?

Also in the PR I replaced a bunch of instances of daoAddress with auctionAddress, and changed certain types just to get to the point where I could try to test if the new component I wrote ran the same as the old one.

Going to take another crack at this in the AM, specifically just tying to build the actual sample app locally, and then going to continue thinking about the provider pattern, given we'll eventually have a provider for each of the 5 contracts that makes up a Nounish DAO. How does the general DAO details provider fit into the other providers. Do they use that provider themselves, or does each component use multiple depending on what it is attempting to accomplish?

**Comment by salieflewis** [comment]
The next step would be rewriting the hooks or components to use these providers. This is a bit of what I'm unsure about, are the providers only meant to be consumed by the components?

**Review by dblodorn — CHANGES_REQUESTED** [review]
Hey @salieflewis! looked this over, i think this starts to establish the pattern well.

I pushed up an addition with an example page, consuming the exported providers / hooks.
Would be cool to see them in action - there is RawDisplayer component which is handy for printing returned data.

Perhaps you and @Valcoholics could use the example app as a place to do documentation and surface aspects of how the code works as it gets added to - also serves as a testing surface of sorts!

**Comment by dblodorn** [comment]
@salieflewis i did hit an import error from the example app - i may not have exported correctly.
But in general might as well use that app as a place to surface progress.

**Pull request closed without merging**
